# Site Settings
baseurl: ""
url : "https://iamispra.github.io"

# Blog Settings
theme_settings :
  title : I am Isuru Prabath
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/isuru_prabath.jpg
    username : Isuru Prabath
    description : Hello World, I am Isuru Prabath. A Self taught Game Developer and a Programmer. 
    experience :
      - start : 2014-08-00
        end : 2018-07-20
        experience : Indie Game Developer/ Freelance Mobile Developer
      - start : 2018-07-20
        end : Present
        experience : Four Corners Software, Software Engineer
    awards :
      - date : 2015-04-00
        title : Mozilla App of the Month Winner
    skills : 
      - skill : Android (Java/ Kotlin)
        value : 90  # Percent value
      - skill : Android (Flutter)
        value : 50  # Percent value  
      - skill : Android (Xamarin)
        value : 50  # Percent value
      - skill : Android (React Native)
        value : 50  # Percent value
      - skill : Unity Game Development
        value : 80  # Percent value
      - skill : Blender
        value : 50 # Percent value
      - skill : C#
        value : 75  # Percent value
      - skill : HTML, CSS & JS
        value : 85  # Percent value
      - skill : PHP
        value : 85  # Percent value
      - skill : JavaFX
        value : 80  # Percent value
      - skill : Construct 2
        value : 90 # Percent value
        
  # Icons
  icons :
    email:  "hello@isuru.info"
    linkedin:  # Full URL 
    github: IamIsPra
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: IamIsPra
    youtube:
    facebook: isuru.prabath
    instagram: IamIsPra

  # Disqus
  disqus_shortname : isuruprabath

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
